config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :line_items

  resources :carts

  resources :products

   root 'products#index'

  get 'login' => "sessions#new", as: :login

  post 'login' => "sessions#create"

  patch 'logout' => "sessions#destroy", as: :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w(Пользователь Модератор Администратор)
  has_secure_password
  before_validation :set_default_role
  validates :password, length: {minimum: 6}, if: "password.present?"
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :role, presence: true, inclusion: {in: 0...ROLES.size}

  def moderator?
    role==1 || administrator?
  end
  def administrator?
    role==2
  end
  def user?
    role==0
  end

  def set_default_role
    self.role||=0
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    session[:user_id]=@user.id
    if @user.save
      redirect_to root_path, notice: 'Вы успешно зарегистрированы.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Пользователь успешно изменён.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Пользователь успешно удалён.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :phone_number, :adress)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  =error_messages_for(@user)
  .form-group
    .fa.fa-envelope.li
    =f.label :email
    =f.email_field :email, class: "form-control"
  .form-group
    .fa.fa-key.li
    = f.label :password
    = f.password_field :password, class: "form-control"
  .form-group
    .fa.fa-key
    .fa.fa-key.li
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "form-control"
  .form-group
    .fa.fa-phone.li
    = f.label :phone_number
    = f.text_field :phone_number, class: "form-control"
  .form-group
    .fa.fa-home.li
    = f.label :adress
    = f.text_area :adress, class: "form-control"
  -#.form-group
  -#  = f.label :role
  -#  = f.number_field :role, class: "form-control"
  .actions
    = f.submit 'Зарегистрироваться', class: "btn btn-primary"

app/views/users/edit.html.haml
%h1 Редактирование пользователя

= render 'form'

= link_to 'Показать', @user
\|
= link_to 'Назад', users_path

app/views/users/index.html.haml
.page-header
  <h1>Список пользователей</h1>

%table.table.table-bordered.table-hover
  %thead
    %tr
      %th
        .fa.fa-envelope.li
          Эл. почта
      %th
        .fa.fa-key.li
          Пароль
      %th
        .fa.fa-phone.li
          Номер телефона
      %th
        .fa.fa-home.li
          Адрес
      %th
        .fa.fa-street-view.li
          Роль
      %th
      %th
      %th
      
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.password
        %td= user.phone_number
        %td= user.adress
        %td= user.role
        %td
          = link_to user, class: "btn btn-link" do
            =fa_icon "arrow-circle-right"
            Показать
        %td
          = link_to edit_user_path(user), class: "btn btn-link" do
            =fa_icon "edit"
            Редактировать
        %td
          = link_to user, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-link" do
            =fa_icon "remove"
            Удалить

.br

= link_to new_user_path, class: "btn btn-primary" do
  =fa_icon "user-plus"
  Новый пользователь

app/views/users/new.html.haml
%h1 Регистрация нового пользователя

= render 'form'

= link_to 'Назад', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Эл. почта:
  = @user.email
%p
  %b Пароль:
  = @user.password
%p
  %b Номер:
  = @user.phone_number
%p
  %b Адрес:
  = @user.adress
%p
  %b Роль:
  = @user.role

= link_to 'Редактировать', edit_user_path(@user)
\|
= link_to 'Назад', users_path