config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :line_items

  resources :carts

  resources :products

   root 'products#index'

  get 'login' => "sessions#new", as: :login

  post 'login' => "sessions#create"

  patch 'logout' => "sessions#destroy", as: :logout

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, ->{includes(:product).order(:created_at)}, dependent: :destroy

  def add_item(p)
    line_item = line_items.where(product_id: p.id).first
    unless line_item
      line_item = self.line_items.build(product: p, quantity: 0, price: p.price)
    end
    line_item.quantity+=1
    line_item.save
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to @cart, notice: 'Корзина создана.'
    else
      render :new
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Корзина изменена.'
    else
      render :edit
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id==session[:cart_id]
    session[:cart_id]=nil
    redirect_to root_path, notice: 'Корзина очищена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Сохранить'

app/views/carts/edit.html.haml
%h1 Редактирование корзины

= render 'form'

= link_to 'Показать', @cart
\|
= link_to 'Назад', carts_path

app/views/carts/index.html.haml
%h1 Список корзин

%table
  %thead
    %tr
      %th
      %th
      %th
      
  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Показать', cart
        %td= link_to 'Редактировать', edit_cart_path(cart)
        %td= link_to 'Удалить', cart, :method => :delete, :data => { :confirm => 'Вы уверены?' }

%br

= link_to 'Новая корзина', new_cart_path

app/views/carts/new.html.haml
%h1 Новая корзина

= render 'form'

= link_to 'Назад', carts_path

app/views/carts/show.html.haml
-#%p#notice= notice
.page-header
  .fa.fa-shopping-cart.fa-4x.li
    Ваша корзина

.row
  .col-md-3
    .list-group
      .list-group-item.active
        .fa.fa-pencil.li
          Название
      .list-group-item
        .fa.fa-info-circle.li
          Описание
      .list-group-item
        .fa.fa-ruble.li
          Цена
      .list-group-item
        .fa.fa-tags.li
          Количество
      .list-group-item
        .fa.fa-download.li
          Общий вес

.row
  - @cart.line_items.each do |item|
    .col-md-3
      .list-group
        .list-group-item.active
          .fa.fa-pencil.li
            #{item.product.name}
        .list-group-item
          .fa.fa-info-circle.li
            #{item.product.description}
        .list-group-item
          .fa.fa-ruble.li
            #{number_to_currency(item.price*item.quantity, separator: ",", delimiter: "", format: "%n")}
        .list-group-item
          .fa.fa-tags.li
            #{item.quantity} шт
            %span.btn.btn-group
              =link_to line_item_path(id:item.id, place:"cart"), class: 'btn btn-default', data: {method: :delete, confirm: 'Вы уверены?'} do
                =fa_icon "minus"
              =link_to line_items_path(id:item.id, place:"cart"), class: 'btn btn-default', data: {method: :post} do
                =fa_icon "plus"
        .list-group-item
          .fa.fa-download.li
            #{number_to_human(item.product.weight*item.quantity, units: {unit: "г", thousand: "кг"})}

.row
  .col-md-4
    .list-group
      .list-group-item
        .fa.fa-list.li
          Итого:
      .list-group-item
        .fa.fa-info-circle.li
          Всего товарных позиций: #{@cart.line_items.length}
        .br
        .li
          Всего товаров:
          -sum=0;@cart.line_items.each{|itm| sum+=itm.quantity}
          #{sum}
        .br
        .li
          Суммарный вес:
          -sum=0;@cart.line_items.each{|item| sum+=item.product.weight*item.quantity}
          #{number_to_human(sum, units: {unit: "г", thousand: "кг"})}
      .list-group-item
        .fa.fa-ruble.li
          Цена:
        -sum=0;@cart.line_items.each{|item| sum+=item.price*item.quantity}
        #{number_to_currency(sum, separator: ",", delimiter: "", format: "%n")}

-#= link_to 'Редактировать', edit_cart_path(@cart), class: "btn btn-link"
= link_to @cart, data:{method: :delete, confirm: "Вы уверены?"}, class: "btn btn-primary" do
  =fa_icon "times-circle"
  Очистить корзину
= link_to root_path, class: "btn btn-info" do
  =fa_icon "external-link-square"
  Вернуться к выбору товаров
= link_to products_path, class: "btn btn-danger disabled" do
  =fa_icon "money"
  Оформить заказ