config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :line_items

  resources :carts

  resources :products

   root 'products#index'

  get 'login' => "sessions#new", as: :login

  post 'login' => "sessions#create"

  patch 'logout' => "sessions#destroy", as: :logout

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :set_current_user
  before_action :set_locale

  protect_from_forgery with: :exception
  before_action :set_cart

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  private
    def set_current_user
      if session[:user_id].present?
        @current_user=User.find(session[:user_id])
      end
    end

    def require_login
      if @current_user
        flash[:danger]='Требуется авторизация'
        redirect_to login_path
      end
    end

    def manager_permission
      unless @current_user.try(:manager?)
        flash[:danger]="Недостаточно прав"
        redirect_to login_path
      end
    end

  def admin_permission
    unless @current_user.try(:admin?)
      flash[:danger]="Недостаточно прав"
      redirect_to login_path
    end
  end

    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render "error_messages", object: object
  end
  def lang_switcher
    content_tag(:ul, class: 'lang-switcher clearfix') do
      I18n.available_locales.each do |loc|
        locale_param = request.path == root_path ? root_path(locale: loc) : params.merge(locale: loc)
        concat content_tag(:li, (link_to loc, locale_param), class: (I18n.locale == loc ? "active" : ""))
      end
    end
  end
end

app/views/application/_error_messages.html.haml
-if object.errors.any?
  .panel.panel-danger
    .panel-heading При сохранении произошли ошибки!
  .panel-body
    %ul
      - object.errors.full_messages.each do |msg|
        %li=msg

app/views/application/_flash_messages.html.haml
-flash.each do |key,val|
  .alert{class: "alert-#{key}"}=val

app/views/application/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      =link_to ?#, class: "navbar-toggle collapsed", data: {toggle: "collapse", target:"#menu"} do
        =fa_icon 'bars'
      =link_to "Магазин", root_path, class: "navbar-brand"
    #menu.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Все товары", products_path
        %li= link_to "Корзина", line_items_path
      %ul.nav.navbar-nav.navbar-right
        -if @current_user.blank?
          %li= link_to "Войти", login_path
        -else
          %li
            %span.navbar-text
              .text-info=@current_user.email
            = link_to "Выйти", logout_path, data:{method: :patch}