config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :line_items

  resources :carts

  resources :products

   root 'products#index'

  get 'login' => "sessions#new", as: :login

  post 'login' => "sessions#create"

  patch 'logout' => "sessions#destroy", as: :logout

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items, dependent: :nullify
  before_destroy :can_destroy?

  validates :name, presence: true, length: {maximum: 200}
  validates :price, presence: true, numericality:{greater_than: 0}
  validates :weight, numericality:{only_integer: true, greater_than: 0}, allow_blank: true

  def can_destroy?
    line_items.blank?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    #respond_to do |format|
      if @product.save
        redirect_to @product
        #format.html { redirect_to @product, notice: 'Продукт успешно создан.' }
        #format.json { render :show, status: :created, location: @product }
      else
        render :new
        #format.html { render :new }
        #format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Продукт успешно изменен.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Продукт успешно уничтожен.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :weight)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
-#.row.pull-right.col-md-3{style: "white-space: nowrap"}
-#  .glyphicon.glyphicon-chevron-right
-#  -@sum,@sum2=0,0;@cart.line_items.each{|itm| @sum+=itm.quantity;@sum2+=itm.price*itm.quantity}
-#  = link_to "В вашей корзине #{@sum} #{Russian.p(@sum,'товар','товара','товаров')}. Общая цена: #{number_to_currency(@sum2, separator: ",", delimiter: "", unit: "₽", format: "%n %u")}", @cart, class: "btn btn-danger", :style => "white-space:normal; width: 216px;"
= form_for @product do |f|
  =error_messages_for(@product)
  .row
    .col-md-3
      .form-group
        =f.label :name
        =f.text_field :name, class: "form-control"
    .col-md-3
      .form-group
        =f.label :description
        =f.text_area :description, class: "form-control"
  .row
    .col-md-3
      .form-group
        =f.label :price
        .input-group
          =f.text_field :price, class: "form-control"
          %span.input-group-addon.glyphicon.glyphicon-ruble
    .col-md-3
      .form-group
        =f.label :weight
        .input-group
          =f.text_field :weight, class: "form-control"
          %span.input-group-addon г.
  .actions=f.submit nil, class: "btn btn-primary"

app/views/products/edit.html.haml
%h1 Редактирование продукта

= render 'form'

= link_to 'Показать', @product
\|
= link_to 'Назад', products_path

app/views/products/index.html.haml
.page-header
  <h1>Продукты</h1>
-#.row.pull-right.col-md-3{style: "white-space: nowrap"}
-#  .glyphicon.glyphicon-chevron-right
-#  -@sum,@sum2=0,0;@cart.line_items.each{|itm| @sum+=itm.quantity;@sum2+=itm.price*itm.quantity}
-#  = link_to "В вашей корзине #{@sum} #{Russian.p(@sum,'товар','товара','товаров')}. Общая цена: #{number_to_currency(@sum2, separator: ",", delimiter: "", unit: "₽", format: "%n %u")}", @cart, class: "btn btn-danger", :style => "white-space:normal; width: 216px;"

.row.center
  .col-md-3
    .list-group
      .list-group-item.active
        .fa.fa-pencil.li
          Название
      .list-group-item
        .fa.fa-info-circle.li
          Описание
      .list-group-item
        .fa.fa-ruble.li
          Цена
      .list-group-item
        .fa.fa-question-circle.li
          Вес

.row
  - @products.each do |product|
    .col-md-3
      .list-group
        .list-group-item.active
          .fa.fa-pencil.li
            #{product.name}
        .list-group-item
          .fa.fa-info-circle.li
            #{product.description}
        .list-group-item
          .fa.fa-ruble.li
            #{number_to_currency(product.price, separator: ",", delimiter: "", format: "%n")}
        .list-group-item.li
          .fa.fa-question-circle
          #{number_to_human(product.weight, units: {unit: "г", thousand: "кг"})}
        .list-group-item.li
          = link_to product, class: "btn btn-link" do
            =fa_icon "arrow-circle-right"
            Показать
        .list-group-item.li
          = link_to edit_product_path(product), class: "btn btn-link" do
            =fa_icon "edit"
            Редактировать
        .list-group-item.li
          = link_to product, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-link" do
            =fa_icon "remove"
            Удалить
        .list-group-item.li
          = link_to line_items_path(product_id: product.id), class: "btn btn-link", data:{method: :post} do
            =fa_icon "cart-plus"
            Добавить в корзину

.br

= link_to new_product_path, class: "btn btn-primary" do
  =fa_icon "plus"
  Новый продукт
.br
= paginate @products

app/views/products/new.html.haml
%h1 Новый продукт

= render 'form'

= link_to 'Назад', products_path

app/views/products/show.html.haml
%p#notice= notice

.br
.page-header
  .h1=@product.name

-#.row
-#  .pull-right.col-md-3{style: "white-space: nowrap"}
-#    .glyphicon.glyphicon-chevron-right
-#    -@sum,@sum2=0,0;@cart.line_items.each{|itm| @sum+=itm.quantity;@sum2+=itm.price*itm.quantity}
-#    = link_to "В вашей корзине #{@sum} #{Russian.p(@sum,'товар','товара','товаров')}. Общая цена: #{number_to_currency(@sum2, separator: ",", delimiter: "", unit: "₽", format: "%n %u")}", @cart, class: "btn btn-danger", :style => "white-space:normal; width: 216px;"


%p
  %b Название:
  = @product.name
%p
  %b Описание:
  = @product.description
%p
  %b Цена:
  = number_to_currency(@product.price, unit: "\u20BD", separator: ",", delimiter: "", format: "%n %u")
%p
  %b Вес:
  = @product.weight

= link_to line_items_path(product_id: @product.id), data:{method: :post}, class: "btn btn-success" do
  =fa_icon "cart-plus"
  Добавить в корзину
\|
= link_to @cart, class: "btn btn-info" do
  =fa_icon "share"
  Перейти к корзине
\|
= link_to edit_product_path(@product), class: "btn btn-warning" do
  =fa_icon "pencil"
  Редактировать
\|
= link_to products_path, class: "btn btn-primary" do
  =fa_icon "reply"
  Вернуться к списку товаров